name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute all tests
        run: ./tests/ci.sh
